dist: bionic

language: python

branches:
  only:
  - master

matrix:
  include:
  - name: "Python 3.6 - linux"
    env: PYTHON_VERSION=3.6
    os: linux
  - name: "Python 3.7 - linux"
    env: PYTHON_VERSION=3.7
    os: linux
  - name: "Python 3.8 - linux"
    env: PYTHON_VERSION=3.8
    os: linux
  - name: "Lint"
    env: PYTHON_VERSION=3.7
    os: linux
    script:
    - black . --diff --check

addons:
    apt:
        packages:
            - libhidapi-dev
            - libudev-dev
            - libusb-1.0-0-dev
            - bluez
            - bluetooth
            - libbluetooth-dev

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
          OS=Linux ;
      else
          OS=MacOSX ;
      fi ;
      wget https://repo.anaconda.com/miniconda/Miniconda3-latest-$OS-x86_64.sh -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda;
    - export PATH="$HOME/miniconda/bin:$HOME/miniconda/lib:$PATH";
    - conda config --set always_yes yes --set changeps1 no;
    - conda env create -f environment.yml
    - source ~/miniconda/bin/activate pfxtest

install:
    - pip install -r requirements.txt
    - python setup.py install
    
script:
    - cd tests
    - pytest -v

